### PR TITLE
Restructured nativefs module.

### PR DESCRIPTION
**Pull request by roliveri**

### CODE REVIEW

**Comment by roliveri** [comment]
@Fryguy @movitto @jerryk55
Please review.

**Comment by jerryk55** [comment]
Looks ok to me.

**Comment by movitto** [comment]
@roliveri Looks good. Just to confirm there are no functional changes here, merely the thin & thick nativefs modules are refactored so as to:

- standardize 'file_class' and 'dir_class' module names
- define the central / base component-specific FS class in the **component**.rb module (eg thin.rb  & thick.rb)

And this will be the standard we are using for the other virtfs plugins going forward correct?

If so merge away!

**Comment by movitto** [comment]
BTW speaking of block* related matters, has there been any resolution on the virt_disk interface?

To record that layer of interaction (so as to use in the specs) we need the outstanding module which I have a PR for (against virt_disk). Of course this provides simple / barebones functionality assuming a file on the local disk but should suffice for immediate CI / testing purposes.

**Comment by roliveri** [comment]
@movitto Correct, just refactoring, there are no functional changes. I did have to remove two tests. It seems my test code fails to find a block device file on the Travis machine, so I had to remove the block device positive tests for `blockdev?` and `ftype`.

As for the central/base component for the exported FS class, it seems that should be determined by the complexity of the filesystem implementation. For example, for very simple implementations, like `metakitfs`, the filesystem class may be at the top-level: `VirtFS::MetakitFS`. For the more complex filesystems, the FS class may be defined under the namespace: `VirtFS::NativeFS::Thin`, `VirtFS::NativeFS::Thick`, `VirtFS::CamcorderFS::FS`, etc.

As for the `virt_disk` interface - for now, maybe we should duplicate that class in the test code as needed. Once the restructuring is complete, I'll have more time to figure out what should be done with that repo.

**Pull request merged**
